-- ============================================================
-- Swara — Skema database ONLINE (Supabase / Postgres)
-- Cara pakai: paste seluruh isi file ini di SQL Editor
-- project Supabase kamu, lalu klik Run.
--
-- 1) Authentication → Providers → Email  : aktifkan.
--    Opsional: matikan "Confirm email" agar akun langsung aktif.
-- 2) Build aplikasi dengan kredensial:
--    flutter run/build --dart-define=SUPABASE_URL=https://xxx.supabase.co
--                      --dart-define=SUPABASE_ANON_KEY=<anon-key>
-- ============================================================

-- Tabel profil pengguna (1 baris per akun, terhubung ke auth.users)
create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  display_name text default 'Pengguna Swara',
  bio text,
  avatar_key text,
  favorite_genre text,
  created_at timestamptz not null default now()
);

-- Riwayat pemutaran per pengguna
create table if not exists public.play_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  song_id text not null,
  title text,
  artist text,
  cover_url text,
  played_at timestamptz not null default now()
);

create index if not exists play_history_user_idx
  on public.play_history (user_id, played_at desc);

-- Auto-buat baris profil ketika akun baru mendaftar
create or replace function public.handle_new_user()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into public.users (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'display_name',
      split_part(new.email, '@', 1)
    )
  )
  on conflict (id) do update
    set email = excluded.email,
        display_name = coalesce(excluded.display_name, public.users.display_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Aktifkan keamanan baris (RLS)
alter table public.users enable row level security;
alter table public.play_history enable row level security;

-- Kebijakan: tiap user hanya mengelola data miliknya sendiri
create policy "users_insert_own" on public.users
  for insert with check (auth.uid() = id);
create policy "users_select_own" on public.users
  for select using (auth.uid() = id);
create policy "users_update_own" on public.users
  for update using (auth.uid() = id);

create policy "history_select_own" on public.play_history
  for select using (auth.uid() = user_id);
create policy "history_insert_own" on public.play_history
  for insert with check (auth.uid() = user_id);
create policy "history_delete_own" on public.play_history
  for delete using (auth.uid() = user_id);